<a href="https://colab.research.google.com/github/Vanshu2374/data-science-45-days/blob/main/grass3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Data Processing

In [1]:
# handle missing values
import pandas as pd

data = {
        'Name':['Ram','Kamal','Ajay'],
        'Age':[25,None,32],
        'salary':[5000,6000,None]
}
df = pd.DataFrame(data)
print("original DataFrame")
print(df)

# null findout | fillna | dropna
print(df.isnull().sum())

df_drop = df.dropna()
df_drop

# fillna
df['Age'].fillna(df['Age'].mean())
df['salary'].fillna(df['salary'].mean())
print(df)

original DataFrame
    Name   Age  salary
0    Ram  25.0  5000.0
1  Kamal   NaN  6000.0
2   Ajay  32.0     NaN
Name      0
Age       1
salary    1
dtype: int64
    Name   Age  salary
0    Ram  25.0  5000.0
1  Kamal   NaN  6000.0
2   Ajay  32.0     NaN


In [2]:
# encoding
from sklearn.preprocessing import LabelEncoder
#import sklearn as sk
#import sklearn
#from sklearn import *
#from sklearn.preprocessing import *
import pandas as pd
data = {
        'Name':['Ram','Kamal','Ajay','Vanshika','Kavi','Sapu'],
        'Age':[25,None,32,20,21,22],
        'salary':[5000,6000,None,7000,8000,9000],
        'Gender':['male','male','male',None,'female','female']
}

df = pd.DataFrame(data)
print("original dataframe")
print(df)

#label encoder
Le = LabelEncoder()
df_label = df.copy()
df_label['Gender'] = df['Gender'].fillna('unknown')
df_label['Gender_encoder'] = Le.fit_transform(df_label['Gender'])
print("After label encoding:")
print(df_label)

original dataframe
       Name   Age  salary  Gender
0       Ram  25.0  5000.0    male
1     Kamal   NaN  6000.0    male
2      Ajay  32.0     NaN    male
3  Vanshika  20.0  7000.0    None
4      Kavi  21.0  8000.0  female
5      Sapu  22.0  9000.0  female
After label encoding:
       Name   Age  salary   Gender  Gender_encoder
0       Ram  25.0  5000.0     male               1
1     Kamal   NaN  6000.0     male               1
2      Ajay  32.0     NaN     male               1
3  Vanshika  20.0  7000.0  unknown               2
4      Kavi  21.0  8000.0   female               0
5      Sapu  22.0  9000.0   female               0


In [3]:
# one hot encoding
import pandas as pd
data = {
        'colors':['red','blue','green','red','blue']
}

df = pd.DataFrame(data)
print("original data")
print(df)

# one hot encoding
encoded_df = pd.get_dummies(df['colors'])

print("after one hot encoding")
print(encoded_df)

original data
  colors
0    red
1   blue
2  green
3    red
4   blue
after one hot encoding
    blue  green    red
0  False  False   True
1   True  False  False
2  False   True  False
3  False  False   True
4   True  False  False


In [9]:
import pandas as pd
data = {
        'colors':['red','blue','green','red','BLUE']
}

df = pd.DataFrame(data)
print("original data")
print(df)

# one hot encoding
encoded_df = pd.get_dummies(df['colors'])

print("after one hot encoding")
print(encoded_df)

original data
  colors
0    red
1   blue
2  green
3    red
4   BLUE
after one hot encoding
    BLUE   blue  green    red
0  False  False  False   True
1  False   True  False  False
2  False  False   True  False
3  False  False  False   True
4   True  False  False  False


In [35]:
# handle missing values
from sklearn.preprocessing import LabelEncoder
import pandas as pd
import numpy as np
data = {
      "colors":['red','green','blue','orange','green','blue',np.nan]
}

df = pd.DataFrame(data)
#print(df)

# handle null values
df.dropna(inplace=True)
print(df)

   colors
0     red
1   green
2    blue
3  orange
4   green
5    blue


In [37]:
# label encoding
from sklearn.preprocessing import LabelEncoder

# method1
le = LabelEncoder()
df['colors_encoder1'] = le.fit_transform(df['colors'])

# method2
df['colors_encoder2'] = LabelEncoder().fit_transform(df['colors'])
#print(df)

# method3
import sklearn
df['colors_encoder3'] = sklearn.preprocessing.LabelEncoder().fit_transform(df['colors'])
print(df)

   colors  colors_encoder  colors_encoder1  colors_encoder2  colors_encoder3
0     red               3                3                3                3
1   green               1                1                1                1
2    blue               0                0                0                0
3  orange               2                2                2                2
4   green               1                1                1                1
5    blue               0                0                0                0


In [50]:
# one hot encoding
from sklearn.preprocessing import OneHotEncoder
print(df)

# drop cols of label encoding
if'colors_encoder' in df.keys():
 df.drop(df[['colors_encoder','colors_encoder1','colors_encoder2','colors_encoder3']],axis=1,inplace=True)

print(df)

# one hot encoding (by the help of sklearn)
encoder = OneHotEncoder()
encoded = encoder.fit_transform(df[['colors']])
print(encoded.toarray())

# one hot encoding (by the help of pandas)
df_encoder = pd.get_dummies(df['colors'])
print(df_encoder)


   colors
0     red
1   green
2    blue
3  orange
4   green
5    blue
   colors
0     red
1   green
2    blue
3  orange
4   green
5    blue
[[0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]
    blue  green  orange    red
0  False  False   False   True
1  False   True   False  False
2   True  False   False  False
3  False  False    True  False
4  False   True   False  False
5   True  False   False  False


In [61]:
# combination of handle missing values | label encoding | one hot encoding
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder , OneHotEncoder

data = {
     "age":[10,20,np.nan,26,30],
     "gender":['male','female','others','male',np.nan],
     "name":['dheeraj','kavi','sapu','yash','hello']
}

df = pd.DataFrame(data)

# handle missing values
df['age'] = df['age'].fillna(df['age'].mean())
df.dropna(subset=['gender'],inplace=True)
print(df)

# label encoding
le = LabelEncoder()
df['gender1'] = le.fit_transform(df['gender'])
print(df)

# one hot encoding
oe = OneHotEncoder()
oe_e = oe.fit_transform(df[['gender']]).toarray()
print(oe_e)

    age  gender     name
0  10.0    male  dheeraj
1  20.0  female     kavi
2  21.5  others     sapu
3  26.0    male     yash
    age  gender     name  gender1
0  10.0    male  dheeraj        1
1  20.0  female     kavi        0
2  21.5  others     sapu        2
3  26.0    male     yash        1
[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
